import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n
  .use(initReactI18next)
  .init({
    resources: {
      uz: {
        translation: {
          technicalissue_detail:"Texnik muammoga duch keldingizmi?",
          technical_issue_details: "Texnik muammoni batafsil yoritib bering!",
          project_duration: "Loyihaning davomiyligi qancha?",
          project_duration_details: "Loyihaning davomiyligi murakkablik va talablar asosida o'zgaradi, lekin odatda 2-4 hafta davom etadi.",
          refund_policy: "Agar mamnun bo'lmasam, pulimni qaytarib olsam bo'ladimi?",
          refund_policy_details: "Ha, bizda qaytarish siyosati mavjud bo'lib, ma'lum shartlar asosida pulni qaytarib olish mumkin. Batafsil ma'lumot uchun biz bilan bog'laning.",
          elizabeth_title: "Backend Developer",
          elizabeth_description: "Jamoamizning eng yaxshi muammo yechuvchilardan biri.",
          john_title: "Frontend Developer",
          john_description: "Yuqori UI ko‘nikmalarga ega ijodiy front-end developer.",
          alice_title: "UI/UX Designer",
          alice_description: "Intuitiv va foydalanuvchilar uchun qulay interfeyslar yaratadi.",
          mike_title: "Project Manager",
          mike_description: "Loyihalarni aniq tasavvur bilan muvaffaqiyatli yakunlaydi.",
          problem_details: "Muammo tafsilotlari",
          your_name: "Ismingiz",
          portfolio: "Portfolio",
          services: "Xizmatlar",
          have_a_question: "Savolingiz bormi?",
          technical_issue: "Texnik muammo",
          issue: "Muammo",
          projects: "Loyihalar",
          experience: "Tajriba",
          description5: "Yuqori darajadagi xizmat, hamma narsa o'z vaqtida amalga oshirildi va kutganimizdan oshib ketdi!",
          description4: "Ularning tajribasi loyihamizga yangi cho'qqilarni zabt etishga yordam berdi, albatta tavsiya qilaman!",
          description3: "Haqiqatan ham g'amxo'rlik qiladigan professionallar bilan ishlash ajoyib tajriba!",
          description2: "Jamoa bilan ishlash juda ko'p tajriba olib keldi va har bir loyiha amalga oshirildi!",
          meetyheteam: "JAMOA BILAN TANISHING",
          see_our_company: "Bizning kompaniyamizga qarang",
          description1: " iPro veb-dizayn kompaniyasi va raqamli marketing agentligiga qaratilgan onlayn o'sib borayotgan brendlar. Biz samarali brend strategiyalarini yaratamiz, maxsus veb-dizayn, ishlab chiqish va raqamli marketing echimlari ko'proq brendni jalb qilish va konversiyalarni yaratish.",
          who_are_we: "BIZ KIMMIZ",
          speak_expert: "Mutaxassis bilan gaplashing",
          marketing_services: "Marketing, boshqa xizmatlar",
          custom_websites: "Maxsus veb-saytlar, mobil ilovalar, brending va raqamli",
          brands_growth: "Brendlarning o'sishi",
          premium_web_design: "Premium veb-dizayn agentligi",
          your_rejected: "Loyihangiz rad etildi",
          your_approved: "Loyihangiz tasdiqlandi",
          careers: "Karyera",
          team: "Jamoa",
          news: "Yangiliklar",
          NEWS_BIG: "YANGILIKLAR",
          services_BIG: "XIZMATLAR",
          workers_BIG: "HODIMLAR",
          services: "Xizmatlar",
          ipro_about: "IPRO haqida",
          workers: "Hodimlar",
          vacancies: "Vakansiyalar",
          about: "Biz Haqimizda",
          contact: "Bog'lanish",
          search: "Qidirish",
          language: "Tilni o'zgartirish",
          hero_title: "IT mutaxassislaridan qulayliklarni",
          hero_subtitle: "taklif qilamiz",
          contact: "Bog’lanish",
          company_name: "IPIMM professional group",
          companyname: "Firma nomi",
          news_title: "Yangiliklar",
          news_button: "Batafsil",
          news_date: "10.11.2023",
          news_description:
            "Internetga 200 mingdan ortiq o‘zbekistonlik foydalanuvchilarning ma’lumotlari sizdirildi. Kun.uz bilan gaplashgan mutaxassislarga ko‘ra, sizdirilgan parollar – OneID, DTM.",
          services_title: "Xizmatlarimiz",
          order_button: "Buyurtma berish",
          details_button: "Batafsil",
          safe: "XAVFSIZ",
          grow: "RIVOJLANTIRING",
          market: "o’rningizni EGALLANG",
          right_choice: "ADASHMADINGIZ",
          with_us: "Biz bilan barchasi",
          improve_business: "Biznesingizni yanada",
          take_place: "Dunyo bozorida o’z",
          choose_us: "SIZ bizni tanlab",
          marquee_text:
            "IT xizmatlarimiz doimiy ravishda yangilanib turadi, yangi texnologiyalar va tizimlar foydalanishga tayyor bo'lib turadi",
          workers_title: "Hodimlar",
          workers_all: "Barchasi →",
          contact: "Bog’laning",
          address: "O'zbekiston, Andijon, A.Fitrat ko'chasi 8",
          links: "Linklar",
          social_media: "Ijtimoiy tarmoqlar",
          // Lavozimlar
          graphic_designer: "Grafik dizayner",
          web_developer: "Web dasturchi",
          backend_developer: "Backend dasturchi",
          ui_ux_designer: "UI/UX dizayner",
          project_manager: "Loyiha menejeri",
          marketing_specialist: "Marketing mutaxassisi",
          qa_engineer: "QA muhandisi",
          devops_engineer: "DevOps muhandisi",
          business_analyst: "Biznes analitik",
          frontend_developer: "Frontend dasturchi",
          data_scientist: "Ma'lumotlar olimi",
          hr_manager: "HR menejeri",
          moution_designe: "Moushen Dizayn",
          video_montage: "Video Montaj",
          telegram_bot: "Telegram Bot",
          programming: "Dasturlash",
          mobile_applications: "Mobile ilovalar",
          targeting: "Targeting",
          marketing: "Marketing",


          // /////////////////////////////////////////////////////////////
          employees_title: "Hodimlar",
          join_our_team: "BIZNING JAMOADA BO’LISHNI ISTAYSIZMI?",
          full_name: "Ism/Familiya",
          region: "Viloyat",
          salary: "Ish haqi",
          profession: "Kasb turi",
          level: "Daraja",
          employment_type: "Bandlik turi",
          phone_number: "Telefon raqami",
          service_type: "Xizmat turi",
          comentary: "Izoh",
          portfolio: "Portfolio",
          upload_cv: "CV joylash",
          submit: "Yuborish",
          Ordering: "Buyurtma berish",
          Detail: "Batafsil",
          Projects: "Loyihalar",
          Partners: "Hamkorlik",
          achievements: "HODIMLAR",
          Year: "Yil",
          send: "Yuborish",
          text_support: "IT sohasida xalqaro standartlarni qo'llab-quvvatlaymiz",
          card_text_1:
            "Bizning IT xizmatlarimiz foydalanish uchun oddiy va qulay",
          card_text_2:
            "Kompaniyamiz doimiy ravishda xizmat sifatini oshirishga intilamiz",
          card_text_3:
            "Mijozlarni IT muammolari bo‘yicha yuqori saviyaga ega texnik yordam bermoqdamiz",
          card_text_4: "Mijozlarimizga eng yaxshi va tezkor yordam bermoqdamiz",
          card_text_5:
            "Texnologiyalar sohasida biz innovatsion yondashuvlarni amalga oshiramiz",
          card_text_6:
            "Biz IT muammolari uchun operativ yechimlarni taqdim etamiz",
          adversiting: "Frontend dasturchisi-VueJS, Javascript, React (Junior)",
          days: "DUSHANBA-SHANBA",
          Samarqand: "Samarqand",
          Toshkent: "Toshkent",
          Fargona: "Farg'ona",
          Andijon: "Andijon",
          Xorazm: "Xorazm",
          Namangan: "Namangan",
          QoraqalpogistonR: "Qoraqalpogiston",
          Buxoro: "Buxoro",
          Navoiy: "Navoiy",
          Jizzax: "Jizzax",
          Surxondaryo: "Surxondaryo",
          Qashqadaryo: "Qashqadaryo",
          Error: "*Xatolik",
          home: "Bosh sahifa",
          success_message: "Muvaffaqiyatli jo'natildi!",
          opening: `
          <span style="color: #ffc700; display: block; margin-bottom: 15px;">Toshkentda yangi ofis,</span>
          <span style="display: block;">ochilishi</span>
        `,
        },
      },
      en: {
        translation: {
          technicalissue_detail:"Are you experiencing a technical problem?",
          technical_issue_details: "Please provide details about the technical issue!",
          project_duration: "How long does a project take?",
          project_duration_details: "Project duration depends on the complexity and requirements, but generally it takes around 2-4 weeks.",
          refund_policy: "Can I get a refund if I'm not satisfied?",
          refund_policy_details: "Yes, we have a refund policy that allows refunds under certain conditions. Please contact us for more details.",
          elizabeth_title: "Backend Developer",
          elizabeth_description: "One of the most problem-solving members of our team.",
          john_title: "Frontend Developer",
          john_description: "Creative front-end developer with strong UI skills.",
          alice_title: "UI/UX Designer",
          alice_description: "Designs intuitive and user-friendly interfaces.",
          mike_title: "Project Manager",
          mike_description: "Leads projects to successful completion with a clear vision.",
          problem_details: "Problem Details",
          your_name: "Ваше имя",
          portfolio: "Portfolio",
          services: "Services",
          have_a_question: "Have a question?",
          technical_issue: "Technical issue",
          issue: "Issue",
          projects: "Projects",
          experience: "Experience",
          meetyheteam: "MEET THE TEAM",
          see_our_company: "See Our Company",
          description5: "Top-notch service, everything was done on time and exceeded our expectations!",
          description4: "Their expertise helped our project reach new heights, would definitely recommend!",
          description3: "A great experience working with professionals who truly care about!",
          description2: "Working with the team brought a lot of experience and each project was done!",
          description1: " iPro is a web design company & digital marketing agency focused on growing brands online. We create effective brand strategies, custom web design, development, and digital marketing solutions to generate greater brand engagement and conversions.",
          who_are_we: "WHO ARE WE",
          speak_expert: "Speak with Expert",
          marketing_services: " Marketing, other services",
          custom_websites: "Custom Websites, Mobile Apps, Branding & Digital",
          brands_growth: " Brands Growth",
          premium_web_design: " Premium Web Design Agency",
          your_rejected: "Your project rejected",
          your_approved: "Your project approved ",
          careers: "Careers",
          team: "Team",
          news: "News",
          NEWS_BIG: "News",
          services_BIG: "SERVICES",
          workers_BIG: "WORKERS",
          services: "Services",
          workers: "Workers",
          ipro_about: "About IPRO",
          vacancies: "Vacancies",
          about: "About Us",
          contact: "Contact Us",
          search: "Search",
          language: "Switch Language",
          hero_title: "We offer convenience from IT specialists",
          hero_subtitle: "",
          contact: "Contact",
          text_support: "We support international standards in the IT sector",
          company_name: "IPIMM professional group",
          companyname: "Company Name",
          news_title: "News",
          news_button: "More",
          news_date: "10.11.2023",
          news_description:
            "Data of more than 200,000 Uzbek users was leaked online. According to experts who spoke to Kun.uz, the leaked passwords belong to OneID, DTM.",
          services_title: "Our Services",
          order_button: "Order Now",
          details_button: "Details",
          safe: "SAFE",
          grow: "GROW",
          market: "TAKE YOUR PLACE",
          right_choice: "YOU MADE THE RIGHT CHOICE",
          with_us: "With us, everything is",
          improve_business: "Improve your business",
          take_place: "Take your place in the global market",
          choose_us: "By choosing us",
          marquee_text:
            "Our IT services are constantly being updated, new technologies and systems are ready for use",
          workers_title: "Workers",
          workers_all: "See All →",
          contact: "Contact",
          address: "Uzbekistan, Andijan, A. Fitrat street 8",
          links: "Links",
          social_media: "Social Media",
          // Job titles
          graphic_designer: "Graphic Designer",
          web_developer: "Web Developer",
          backend_developer: "Backend Developer",
          ui_ux_designer: "UI/UX Designer",
          project_manager: "Project Manager",
          marketing_specialist: "Marketing Specialist",
          qa_engineer: "QA Engineer",
          devops_engineer: "DevOps Engineer",
          business_analyst: "Business Analyst",
          frontend_developer: "Frontend Developer",
          data_scientist: "Data Scientist",
          hr_manager: "HR Manager",
          moution_designe: "Moution Designe",
          video_montage: "Video Montage",
          telegram_bot: "Telegram Bot",
          programming: "Programming",
          mobile_applications: "Mobile applications",
          targeting: "Targeting",
          marketing: "Marketing",
          text_support: "We support international standards in the IT sector",
          // ///////////////////////////////////////////////////////////
          employees_title: "Employees",
          join_our_team: "DO YOU WANT TO BE PART OF OUR TEAM?",
          full_name: "Full Name",
          region: "Region",
          salary: "Salary",
          profession: "Profession",
          level: "Level",
          employment_type: "Employment Type",
          phone_number: "Phone Number",
          service_type: "Service type",
          comentary: "Comentary",
          send: "Send",
          portfolio: "Portfolio",
          upload_cv: "Upload CV",
          submit: "Submit",
          Ordering: "Ordering",
          Detail: "Detail",
          Projects: "Projects",
          Partners: "Collaborators",
          achievements: "achievements",
          Year: "Year",
          card_text_1: "Our IT services are simple and easy to use",
          card_text_2:
            "Our company strives to constantly improve the quality of service",
          card_text_3:
            "We provide our clients with high-quality technical support for IT problems.",
          card_text_4: "We provide the best and fastest support to our customers",
          card_text_5:
            "We implement innovative approaches in the field of technology",
          card_text_6: "We provide operational solutions for IT problems",
          adversiting: "Frontend developer-VueJS, Javascript, React (Junior)",
          days: "MONDAY-SATURDAY",
          Samarqand: "Samarkand",
          Toshkent: "Tashkent",
          Fargona: "Fergana",
          Andijon: "Andijan",
          Xorazm: "khorazem",
          Namangan: "Namangan",
          QoraqalpogistonR: "Karakalpakstan",
          Buxoro: "Bukhara",
          Navoiy: "Navoi",
          Jizzax: "Jizzakh",
          Surxondaryo: "Surkhandarya",
          Qashqadaryo: "Kashkadarya",
          Error: "*Error",
          home: "Home",
          success_message: "Successfully sent!",
          opening: "We invite you to the OPENING CEREMONY!",
          opening: `
          <span style="color: #ffc700; display: block; margin-bottom: 15px;">New office in Tashkent,</span>
          <span style="display: block;">opening</span>
        `,
        },
      },
      ru: {
        translation: {
          technicalissue_detail:"У вас возникли технические проблемы?",
          technical_issue_details: "Пожалуйста, подробно опишите техническую проблему!",
          project_duration: "Сколько времени занимает проект?",
          project_duration_details: "Продолжительность проекта зависит от сложности и требований, но обычно занимает около 2-4 недель.",
          refund_policy: "Могу ли я получить возврат, если я не доволен?",
          refund_policy_details: "Да, у нас есть политика возврата, которая позволяет возвраты при соблюдении определённых условий. Пожалуйста, свяжитесь с нами для получения более подробной информации.",
          elizabeth_title: "Backend Developer",
          elizabeth_description: "Один из самых решающих проблемы в нашей команде.",
          john_title: "Frontend Developer",
          john_description: "Креативный фронтенд-разработчик с сильными навыками UI.",
          alice_title: "UI/UX Designer",
          alice_description: "Разрабатывает интуитивно понятные и удобные интерфейсы.",
          mike_title: "Project Manager",
          mike_description: "Руководит проектами к успешному завершению с ясным видением.",
          problem_details: "Подробности проблемы",
          problem_details: "Muammo tafsilotlari",
          your_name: "Your Name",
          portfolio: "Портфолио",
          services: "Услуги",
          have_a_question: "Есть вопрос?",
          technical_issue: "Техническая проблема",
          issue: "Проблема",
          projects: "Проекты",
          experience: "Опыт",
          meetyheteam: "ЗНАКОМЬТЕСЬ С КОМАНДОЙ",
          see_our_company: "Посмотреть нашу компанию",
          description5: "Первоклассный сервис, все было сделано вовремя и превзошло наши ожидания!",
          description4: "Их опыт помог нашему проекту достичь новых высот, определенно рекомендую!",
          description3: "Отличный опыт работы с профессионалами, которые действительно заботятся о вас!",
          description2: "Работа с командой принесла много опыта, и каждый проект был реализован!",
          description1: "iPro — это компания веб-дизайна и агентство цифрового маркетинга, ориентированное на развитие брендов в Интернете. Мы создаем эффективные стратегии бренда, индивидуальный веб-дизайн, разработку и решения цифрового маркетинга для повышения вовлеченности бренда и конверсий.",
          who_are_we: "КТО МЫ",
          speak_expert: "Поговорите с экспертом",
          marketing_services: " Маркетинг, другие услуги",
          custom_websites: "Индивидуальные веб-сайты, мобильные приложения, брендинг и цифровые технологии",
          brands_growth: "Рост брендов",
          premium_web_design: "Агентство премиум-веб-дизайна",
          your_rejected: "Ваш проект отклонен",
          your_approved: "Ваш проект одобрен",
          careers: "Карьера",
          team: "Команда",
          news: "Новости",
          NEWS_BIG: "НОВОСТИ",
          services_BIG: "УСЛУГИ",
          workers_BIG: "ПЕРСОНАЛ",
          services: "Услуги",
          ipro_about: "О ИПРО",
          workers: "Сотрудники",
          vacancies: "Вакансии",
          about: "О нас",
          contact: "Контакты",
          search: "Поиск",
          language: "Изменить язык",
          hero_title: "Мы предлагаем удобства от IT-специалистов",
          hero_subtitle: "",
          contact: "Связаться",
          company_name: "IPIMM профессиональная группа",
          companyname: "Название компании",
          news_title: "Новости",
          news_button: "Подробнее",
          news_date: "10.11.2023",
          news_description:
            "В сеть утекли данные более 200 000 узбекских пользователей. По словам экспертов, говоривших с Kun.uz, утекшие пароли относятся к OneID, DTM.",
          services_title: "Наши услуги",
          order_button: "Заказать",
          details_button: "Подробнее",
          safe: "БЕЗОПАСНО",
          grow: "РАЗВИВАЙТЕ",
          market: "ЗАЙМИТЕ СВОЕ МЕСТО",
          right_choice: "ВЫ НЕ ОШИБЛИСЬ",
          with_us: "С нами всё",
          improve_business: "Развивайте свой бизнес",
          take_place: "Займите свое место на мировом рынке",
          choose_us: "Выбирая нас",
          marquee_text:
            "Наши IT-услуги постоянно обновляются, новые технологии и системы готовы к использованию",
          workers_title: "Сотрудники",
          workers_all: "Все →",
          contact: "Свяжитесь с нами",
          address: "Узбекистан, Андижан, ул. А.Фитрат 8",
          links: "Ссылки",
          social_media: "Социальные сети",

          // Должности
          graphic_designer: "Графический дизайнер",
          web_developer: "Веб-разработчик",
          backend_developer: "Бэкенд-разработчик",
          ui_ux_designer: "UI/UX дизайнер",
          project_manager: "Менеджер проекта",
          marketing_specialist: "Маркетолог",
          qa_engineer: "Инженер по качеству",
          devops_engineer: "DevOps инженер",
          business_analyst: "Бизнес-аналитик",
          frontend_developer: "Фронтенд-разработчик",
          data_scientist: "Специалист по данным",
          hr_manager: "HR-менеджер",
          moution_designe: "Моушен дизайн",
          video_montage: "Видеомонтаж",
          telegram_bot: "Телеграм-бот",
          programming: "Программирование",
          mobile_applications: "Мобильные приложения",
          targeting: "Нацеливание",
          marketing: "Маркетинг",
          // /////////////////////////////////////////////////////////
          employees_title: "сотрудники",
          join_our_team: "ВЫ ХОТИТЕ БЫТЬ ЧАСТЬЮ НАШЕЙ КОМАНДЫ?",
          full_name: "Имя/Фамилия",
          region: "Регион",
          salary: "Зарплата",
          profession: "Профессия",
          level: "Уровень",
          employment_type: "Тип занятости",
          phone_number: "Номер телефона",
          comentary: "Комментарий",
          service_type: "Тип услуги",
          send: "Отправлять",
          portfolio: "Портфолио",
          upload_cv: "Загрузить резюме",
          submit: "Отправить",
          Ordering: "Заказ",
          Detail: "подробно",
          Projects: "Проекты",
          Partners: "партнеры",
          achievements: "достижения",
          Year: "Год",
          text_support: "Мы поддерживаем международные стандарты в сфере ИТ",
          card_text_1: "Наши ИТ-услуги просты и удобны в использовании.",
          card_text_2:
            "Наша компания стремится постоянно улучшать качество обслуживания.",
          card_text_3:
            "Мы оказываем нашим клиентам качественную техническую поддержку по решению ИТ-проблем.",
          card_text_4: "Мы оказываем лучшую и быструю поддержку нашим клиентам",
          card_text_5: "Мы внедряем инновационные подходы в области технологий",
          card_text_6: "Мы предоставляем оперативные решения ИТ-проблем",
          adversiting: "Разработчик интерфейса — VueJS, Javascript, React ",
          days: "ПОНЕДЕЛЬНИК-СУББОТА",
          Samarqand: "Самарканд",
          Toshkent: "Ташкент",
          Fargona: "Фергана",
          Andijon: "Андижан",
          Xorazm: "Хорезм",
          Namangan: "Наманган",
          QoraqalpogistonR: "Каракалпакстан",
          Buxoro: "Бухара",
          Navoiy: "Навои",
          Jizzax: "Джизак",
          Surxondaryo: "Сурхандарья",
          Qashqadaryo: "Кашкадарья",
          Error: "*Ошибка",
          home: "домa",
          success_message: "Успешно отправлено!",
          opening: "Приглашаем Вас на ЦЕРЕМОНИЮ ОТКРЫТИЯ!",
          opening: `
          <span style="color: #ffc700; display: block; margin-bottom: 15px;">Новый офис в Ташкенте,</span>
          <span style="display: block;">открытие</span>
        `,
        },
      },
    },
    lng: 'en', // default language
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
